name: Terraform Apply on dispatch

on: [workflow_dispatch]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Check if all checks passed
        uses: arup-group/action-all-checks-passed@master
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Init
        run: terraform init
      - name: Apply Terraform
        if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize')
        run: |
          terraform apply -auto-approve
          terraform show
          echo "::set-output name=terraform_output::$(terraform output -json)"
          terraform output -json | jq '.' > terraform_output.json
          echo "Terraform apply is done"
      - name: Comment output to PR
        uses: actions/github-script@v6
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const output = `<details><summary>Show Plan</summary>
            \`\`\`\n
            ${{ steps.print_output.outputs.terraform_output }}
            \`\`\`

            </details>

            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
